apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: tarasmats/shop/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: shop-secret
                  key: jwt
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: shop-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shop-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shop-secret
                  key: POSTGRES_USER
          # envFrom:
          #   - secretRef:
          #       name: shop-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
